
# This config file is adapted from the example in the documentation
# https://github.com/marketplace/actions/deploy-to-github-pages#getting-started-airplane

name: Build and Deploy

on:
  push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        # The documentation template that this file is based on had this note:
        # "If you're using actions/checkout@v2 you must set persist-credentials 
        # to false in most cases for the deployment to work correctly."
        with:
          persist-credentials: false

      - name: NPM install ğŸš›
        uses: bahmutov/npm-install@v1
        
      - name: Run Unit Tests âœ”ï¸
        run: |
          npx jest --coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Parcel Build ğŸ“¦
        run: |
          npx parcel build index.html --public-url /${{ github.event.repository.name }}
          cp -r dist build

      - name: Save build/ directory. â˜ï¸
        uses: actions/upload-artifact@v2 
        with:
          name: build
          path: build

      - name: Deploy ğŸš€
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
